### ISSUE TITLE
Reference link incorrect on sdk documentation pt_BR

### ISSUE THREAD

**Issue by brunodix** [awsdocs/aws-java-developer-guide-v2#10]
There is wrong link on this page: _https://docs.aws.amazon.com/pt_br/sdk-for-java/v2/developer-guide/welcome.html_ on pt_BR version.

Item **Referência do AWS SDK para Java 2.x** leads to `https://sdk./java/api/latest/` instead of `https://sdk.amazonaws.com/java/api/latest/`

**Comment by jschwarzwalder** [comment]
Thank you for letting us know. 

We will work to get this fixed.
