### ISSUE TITLE
Need Dynamodb example of getting a range of items for v2.0

### ISSUE THREAD

**Issue by lfarrgouch** [awsdocs/aws-java-developer-guide-v2#24]
Is it possible to get an example in the docs or in the sample project of how to get multiple items for version 2.0 SDK for java ?  In version 1.11 we did it like below using a keyconditionexpression to retrieve a range of data.  Not sure how to translate that into v2.0 code and existing samples are just for getting one item.

AmazonDynamoDB dbc = AmazonDynamoDBClientBuilder.standard().withCredentials(credentialsProvider).withRegion(Regions.fromName(Common.AwsRegion)).build();

        DynamoDB dynamoDB = new DynamoDB(dbc);
        Table table = dynamoDB.getTable("mytable");
        Index index = table.getIndex("utcTs");
        // Note: BETWEEN is inclusive on both ends (the intervals with the timestamp = startdttm and timestamp = enddttm will be returned)
        QuerySpec spec = new QuerySpec()
                .withKeyConditionExpression("spaceId = :spaceId and utcTsEnd BETWEEN :startdttm AND :enddttm")
                .withValueMap(new ValueMap()
                        .withString(":spaceId", spaceId)
                        .withNumber(":startdttm", startMillis)
                        .withNumber(":enddttm", endMillis));

        ItemCollection<QueryOutcome> items = index.query(spec);

        Iterator<Item> iterator = items.iterator();

**Comment by ghost** [comment]
Thanks for your request. I will add it to the team’s list for future consideration and then close this issue accordingly. 

Paul
AWS Documentation
