### ISSUE TITLE
Logging uses SLF4j

### ISSUE THREAD

**Issue by ceefour** [awsdocs/aws-java-developer-guide-v2#3]
https://github.com/awsdocs/aws-java-developer-guide-v2/blob/master/doc_source/java-dg-logging.rst#logging-sdk-java-calls mentions Apache Commons Logging which has been replaced by slf4j as of https://github.com/aws/aws-sdk-java-v2/issues/57#issuecomment-317476490 , https://github.com/aws/aws-sdk-java-v2/pull/66

**Comment by soo-aws** [comment]
Thank you! This topic has been updated.
