### ISSUE TITLE
Incomplete documentation in "Supplying and Retrieving AWS Credentials"

### ISSUE THREAD

**Issue by florianakos** [awsdocs/aws-java-developer-guide-v2#37]
Hello,

This is related to [this](https://github.com/awsdocs/aws-java-developer-guide-v2/blob/base/doc_source/credentials.rst) document which is live under [this](https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/credentials.html) link.

I've recently came across an issue with fetching credentials from a K8s pod running on an AWS EKS cluster. In the application I had an S3 Client using SDK v1 and an Athena client using SDK v2. The S3 client worked fine while the Athena client failed.

Both the `DefaultAWSCredentialsProviderChain` in SDK v1 and the `DefaultCredentialsProvider` in SDK v2 already seem to contain the necessary provider for loading credentials through Web Identity Token file mounted to Pods on EKS under the path **/var/run/secrets/eks.amazonaws.com/serviceaccount/token**:

* [WebIdentityTokenCredentialsProvider](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.java) in SDK v1
* [WebIdentityTokenFileCredentialsProvider](https://github.com/aws/aws-sdk-java-v2/blob/master/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.java) in SDK v2 

However the Developer Guide seems to be out of date as the it only mentions this fact in the [page for SDK v1](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html) but not in the [page for SDK v2](https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/credentials.html).

I thought it would be worthwhile to update the Developer Guide so it mentions the presence of Web Identity Token provider as well as the fact that it needs the STS v2 package on the class-path for it to function.

**Comment by Carey-AWS** [comment]
Thank you for your feedback - we have updated the credentials documentation in the developer guide
