### ISSUE TITLE
For S3 ListObjects it only returns 1000 files, How to set a continuous token on response object.

### ISSUE THREAD

**Issue by rsabde-aarete** [awsdocs/aws-java-developer-guide-v2#41]
` try {
    	        ListObjectsRequest listObjects = ListObjectsRequest
    	                .builder()
    	                .bucket(bucketName)
    	                .build();

    	        ListObjectsResponse res = s3.listObjects(listObjects);
    	        List<S3Object> objects = res.contents();

    	        for (ListIterator iterVals = objects.listIterator(); iterVals.hasNext(); ) {
    	            S3Object myValue = (S3Object) iterVals.next();
    	            System.out.print("\n The name of the key is " + myValue.key());
    	         }

    	    } catch (S3Exception e) {
    	        System.err.println(e.awsErrorDetails().errorMessage());
    	        System.exit(1);
    	    }`

Only returns 1000 s3 objects and no support for setting the continuous token to the request object.

**Comment by RudyBai** [comment]
Hey - I imagine this has been added since - but this is the solution for anyone stumbling upon this since:

```java
   public List<S3ObjectSummary> getAllObjects()
   {
      ListObjectsV2Result listObjectsV2Result = this.s3Client.listObjectsV2(
            new ListObjectsV2Request()
      );
      List<S3ObjectSummary> s3ObjectSummaries = listObjectsV2Result.getObjectSummaries();

      while (listObjectsV2Result.isTruncated())
      {
         ListObjectsV2Request listObjectsV2Request = new ListObjectsV2Request()
               .withContinuationToken(listObjectsV2Result.getNextContinuationToken());
         listObjectsV2Result = this.s3Client.listObjectsV2(listObjectsV2Request);
         s3ObjectSummaries.addAll(listObjectsV2Result.getObjectSummaries());
      }

      return s3ObjectSummaries;
   }
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
