### ISSUE TITLE
No any documentation found for AWS EMR

### ISSUE THREAD

**Issue by LamaBimal** [awsdocs/aws-java-developer-guide-v2#8]
I am migrating Aws sdk version 1.x to version 2.x. I am not getting any documentation for the Aws Emr.

**Comment by jschwarzwalder** [comment]
You can find the API reference for EMR in the [AWS SDK for Java v2 API Reference](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/emr/package-summary.html)
