### ISSUE TITLE
No documentation for Lambda

### ISSUE THREAD

**Issue by kenyons** [awsdocs/aws-java-developer-guide-v2#9]
The classes seem to have changed drastically and there is no documentation.  The package *.*..services.lambda.invoke is completely gone in 2.x and services.lambda.runtime doesn't seem to have been updated.  Also, event classes seem to have gone missing like S3EventNotification.

**Comment by jschwarzwalder** [comment]
Currently the team is working to build parity with the Java SDK v1. 

You can add a commented to the official [AWS SDK for Java GitHub repository](https://github.com/aws/aws-sdk-java-v2) with a feature request if you would like Lambda to be prioritized.
